# Autogenerated wrapper script for Serd_jll for aarch64-apple-darwin
export libserd

JLLWrappers.@generate_wrapper_header("Serd")
JLLWrappers.@declare_library_product(libserd, "@rpath/libserd-0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libserd,
        "lib/libserd-0.0.30.10.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
