# Autogenerated wrapper script for Serd_jll for x86_64-w64-mingw32
export libserd

JLLWrappers.@generate_wrapper_header("Serd")
JLLWrappers.@declare_library_product(libserd, "serd-0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libserd,
        "bin\\serd-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
